### PR TITLE
[WIP] Initial work on fully qualified (schema/db) addressing.

### LINKED ISSUE #100: Support library-specific qualified names
For example: `Sequel::SQL::QualifiedIdentifier` from Sequel.  I'm not sure if Arel/ActiveRecord has a similar syntax.

### LINKED ISSUE #101: Support for fully qualified table names
This has come up before in #53 and is partially fixed in #95.

### Requested Support

- MySQL: Generally (appears) to not be an issue, probably due to it only the edge-case of wanting to upsert to a different database - you'd generally use the connection for the other database instead.  That being said, we might as well add support for `dbname.tablename` for those using MySQL.  We *will* have to make sure that our changes don't cause any regressions :)
- Postgres: As noted in #53 and #95, the demand is there for this.  I also have an internal patch to support this (with Sequel).
- MSSQL: Once MSSQL support is running (I'm hoping sometime this year ... maybe?).  The demand will likely also be there.  See https://technet.microsoft.com/en-us/library/ms187879(v=sql.105).aspx for further information.
- Sqlite3: Use-case would be uncommon, but similar to MySQL - via the [ATTACH](http://sqlite.org/lang_attach.html) keyword.
- Others: We'll likely want to handle those as they occur.  I believe most other larger DBs support db/schema name qualification.

### Syntax

The general syntax for referring to an alternative database/schema is `db_or_schema.table_name`.  However, a period is valid inside a quoted identifier, so passing Just "db.some_table" into Upsert isn't a valid option, as that could equally be a valid database __or__ table name. `"data.base.name"."table.name"` is valid in Postgres 🙄 

I propose that we use an array of String-ish objects to refer to something that's qualified beyond just the table name.  `["database", "table"]` and `[:database, :table]` should both be valid.  Thoughts on just doing `database_object.map(&:to_s)` in general so you can pass anything responding to `to_s`?

### Caveats

1. In playing around with this, it occurred to me that the Postgres Upsert adapter won't work with a fully qualified name (Because it looks up the name as a string, as opposed to an oid).  I imagine there will be other similar edge-cases, so care will need to be taken that we cover all of those.
2. In Postgres (at the very least) quoting an identifier causes it to also be case-sensitive (ref. the note at the very bottom of [4.1.1](https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS)).  This has the potential to be an issue for people upgrading - if we start fully quoting everything then there rises the possibility that applications assuming case-insensitivity no longer work properly.  With that in mind, should we consider the inclusion of this to also push Upsert to v3.0?

### Other

This would need to be done before #100 could be properly supported.

/cc @seamusabshere @devonestes @zakcrawford

### PR DESCRIPTION
**Pull request by pnomolos**
### Still required:

- [x] More specs
- [x] Fix dependency on Sequel in table name check - should only happen if Sequel is available, as it's a dev dependency and will break in pure-AR environments.

- Fixes #100 
- Fixes #101

### CODE REVIEW

**Comment by pnomolos** [comment]
Due to the way that ActiveRecord 3 handles quoting of table names in MySQL, it may actually be impossible to get a proper test suite together until we upgrade those dependencies.

File: lib/upsert.rb [hunk 1]
```diff
@@ -185,7 +185,7 @@ def assume_function_exists?
   # @param [Hash] options
   # @option options [TrueClass,FalseClass] :assume_function_exists (true) Assume the function has already been defined correctly by another process.
   def initialize(connection, table_name, options = {})
-    @table_name = table_name.to_s
+    @table_name = table_name.is_a?(::Sequel::SQL::QualifiedIdentifier) ? [table_name.table, table_name.column] : [*table_name].map(&:to_s)
```
Comment (seamusabshere) [inline lib/upsert.rb]: `Sequel` won't be defined in most apps - perhaps safer to do

```
table_name.class.name == 'Sequel::SQL::QualifiedIdentifier' ? [...]
```

File: lib/upsert/merge_function/postgresql.rb [hunk 2]
```diff
@@ -116,14 +116,18 @@ def server_version
       end
 
       def schema_query
+        table_name_arguments = table_name.is_a?(Array) ? table_name : ["public", table_name]
```
Comment (seamusabshere) [inline lib/upsert/merge_function/postgresql.rb]: i don't think we should assume `public` is at the front of pg's `search_path` ... it would be better to leave it out

(i don't quite understand what's going on, so maybe the addition of the schema is necessary somehow?)

File: lib/upsert/merge_function/postgresql.rb [hunk 3]
```diff
@@ -116,14 +116,18 @@ def server_version
...
+        table_name_arguments.unshift("public") if table_name_arguments.length == 1
+        table_name_arguments << quoted_table_name if table_name_arguments.length == 2
```
Comment (seamusabshere) [inline lib/upsert/merge_function/postgresql.rb]: what does this do?

File: lib/upsert/merge_function/sqlite3.rb [hunk 4]
```diff
@@ -23,6 +33,7 @@ def execute(row)
         bind_update_values = row.setter.select{ |k,v| k !~ CREATED_COL_REGEX }.map { |k,v| connection.bind_value v }
 
         insert_or_ignore_sql = %{INSERT OR IGNORE INTO #{quoted_table_name} (#{quoted_setter_names.join(',')}) VALUES (#{Array.new(bind_setter_values.length, '?').join(',')})}
+        puts [insert_or_ignore_sql, bind_setter_values].inspect
```
Comment (seamusabshere) [inline lib/upsert/merge_function/sqlite3.rb]: debug

File: lib/upsert/merge_function/postgresql.rb (hunk 3 above)
Comment (pnomolos) [reply lib/upsert/merge_function/postgresql.rb]: I'm cleaning this up (and writing some specs for it) - basically we need to make sure that when we're looking for the unique index (I also renamed the function to be clearer) we select the correct table - so use schema if specified and if not use the default search path.

Ex, we have `public.pets` and `other_schema.pets` - we need to search for a unique index on whichever table we're targeting for the UPSERT.

File: lib/upsert.rb [hunk 5]
```diff
@@ -37,6 +37,23 @@ def logger
...
+      retrieve_mutex(upsert.table_name, row.selector.keys, row.setter.keys)
+    end
+
+    def retrieve_mutex(*args)
+      # ||= isn't an atomic operation
+      MUTEX_FOR_PERFORM.synchronize do
+        @mutex_cache ||= {}
+      end
+      cache_key = args.flatten.join('::')
+      @mutex_cache[cache_key] ||= Mutex.new
```
Comment (seamusabshere) [inline lib/upsert.rb]: this probably also has to be inside the mutex

File: lib/upsert/merge_function/postgresql.rb [hunk 6]
```diff
@@ -107,34 +107,53 @@ def sql
       end
 
       def use_pg_native?
-        server_version >= 95 && unique_index_on_selector?
+        @use_pg_native ||= server_version >= 95 && unique_index_on_selector?
```
Comment (seamusabshere) [inline lib/upsert/merge_function/postgresql.rb]: to memoize a boolean, do

```
def foo
  return @foo if defined?(@foo)
  @foo = boolean
end
```

otherwise it will recalculate constantly on false or null

File: spec/correctness_spec.rb [hunk 7]
```diff
@@ -167,6 +175,11 @@
             end
             Pet.import columns, all_values, :timestamps => false, :on_duplicate_key_update => columns
           end
+
+          # We need a better syntax to do this sort of stuff in tests
+          # fail Pet.inline_schema_config.instance_variable_get(:@ideal_indexes).inspect
+          Pet.inline_schema_config.instance_variable_set(:@ideal_indexes, Set.new)  unless UNIQUE_CONSTRAINT
```
Comment (seamusabshere) [inline spec/correctness_spec.rb]: i feel like my ancient `active_record_inline_schema` gem is getting in the way here

in all my new libs / app work, i just use plain sql to create tables / change them

feel free to remove it - maybe see if that clarifies things?

File: spec/fully_qualified_spec.rb [hunk 8]
```diff
@@ -0,0 +1,41 @@
...
+  it "works without a fully qualified name" do
+    upsert = Upsert.new $conn, :pets
+    assert_creates(Pet, [{:name => 'Jerry', :gender => 'male'}]) do
+      upsert.row({:name => 'Jerry'}, {:gender => 'male'})
+    end
+  end
+
+  it "works with a fully qualified name" do
+    table_name = ["#{RawConnectionFactory::DATABASE}2", :pets]
+    cls = clone_ar_class(Pet, table_name)
```
Comment (seamusabshere) [inline spec/fully_qualified_spec.rb]: perhaps define a new class Pet2 instead of metaprogramming?

File: lib/upsert.rb (hunk 5 above)
Comment (pnomolos) [reply lib/upsert.rb]: Good point.

File: lib/upsert/merge_function/postgresql.rb (hunk 6 above)
Comment (pnomolos) [reply lib/upsert/merge_function/postgresql.rb]: Of course!  I'm notorious for forgetting that.

File: spec/correctness_spec.rb (hunk 7 above)
Comment (pnomolos) [reply spec/correctness_spec.rb]: Let's get this release cut, then maybe do a big clean up and move to a version 2?

File: spec/fully_qualified_spec.rb (hunk 8 above)
Comment (pnomolos) [reply spec/fully_qualified_spec.rb]: This seems to be working fine, maybe another thing we can address moving forward since we'll be removing `active_record_inline_schema` anyway?

**Comment by pnomolos** [comment]
@seamusabshere Could I get another review please? :)

File: spec/spec_helper.rb [hunk 9]
```diff
@@ -277,6 +312,27 @@ def assert_faster_than(competition, records, &blk)
...
+    # AR's support for quoting of schema and table names is horrendous
+    # schema.table and schema.`table` are considiered different names on MySQL, but
+    # schema.table and schema."table" are correctly considered the same on Postgres
+    new_table_name[-1] = u.connection.quote_ident(new_table_name[-1]) if new_table_name[-1].to_s.index('.')
+    new_table_name = new_table_name.join('.')
+    cls = Class.new(klass)
+    cls.class_eval do
+      self.table_name = new_table_name
+      def self.quoted_table_name
+        table_name
```
Comment (seamusabshere) [inline spec/spec_helper.rb]: overriding `quoted_table_name` may change behavior significant in a lib that writes sql... necessary?

File: spec/spec_helper.rb [hunk 10]
```diff
@@ -277,6 +312,27 @@ def assert_faster_than(competition, records, &blk)
...
+    u = Upsert.new $conn, klass.table_name
+    new_table_name = [*table_name].compact
+    # AR's support for quoting of schema and table names is horrendous
+    # schema.table and schema.`table` are considiered different names on MySQL, but
+    # schema.table and schema."table" are correctly considered the same on Postgres
+    new_table_name[-1] = u.connection.quote_ident(new_table_name[-1]) if new_table_name[-1].to_s.index('.')
+    new_table_name = new_table_name.join('.')
+    cls = Class.new(klass)
+    cls.class_eval do
+      self.table_name = new_table_name
```
Comment (seamusabshere) [inline spec/spec_helper.rb]: i have never set activerecord's `table_name` to anything other than an unquoted string

is fully qualified schema a supported option?

i just don't know how this would work with (imagine that) `quoted_table_name`... would it detect the quotes? would it parse out the schema?

i would expect

```
# set search_path to "bar"
class Foo < ActiveRecord::Base
  self.table_name = 'foo'
end
```

Now Foo would look in either public.foos or bar.foos

File: spec/spec_helper.rb [hunk 11]
```diff
@@ -1,12 +1,40 @@
...
+      end
+    ))
+  end
+
+  def inline_schema_config
+    return @inline_schema_config if defined?(@inline_schema_config)
+    if superclass != ::ActiveRecord::Base
+      @inline_schema_config = base_class.inline_schema_config.dup
+    else
+      MUTEX.synchronize do
```
Comment (seamusabshere) [inline spec/spec_helper.rb]: for simplicity / lack of surprise, i would wrap this whole thing in the mutex

File: lib/upsert.rb [hunk 12]
```diff
@@ -37,6 +37,31 @@ def logger
...
+    def mutex_for_row(upsert, row)
+      retrieve_mutex(upsert.table_name, row.selector.keys)
+    end
+
+    def mutex_for_function(upsert, row)
+      retrieve_mutex(upsert.table_name, row.selector.keys, row.setter.keys)
+    end
+
+    # TODO: Rewrite this to use the thread_safe gem, perhaps?
+    def retrieve_mutex(*args)
```
Comment (seamusabshere) [inline lib/upsert.rb]: you know, there is an argument that we should just drop all this complicated mutex stuff and change how it's invoked to make it thread safe

File: spec/spec_helper.rb (hunk 9 above)
Comment (pnomolos) [reply spec/spec_helper.rb]: This is only for the spec, and we can remove it when we take a look at removing `active_record_inline_schema` :)

File: spec/spec_helper.rb (hunk 10 above)
Comment (pnomolos) [reply spec/spec_helper.rb]: Depending on database driver (thanks MySQL) it may or may not do funny things with the string.  Was to get the specs passing until we can revisit the whole thing.

File: lib/upsert.rb (hunk 12 above)
Comment (pnomolos) [reply lib/upsert.rb]: That's very true, maybe returning an upsert instance based on the current thread, or something?  That's the problem when using class methods ...

**Comment by pnomolos** [comment]
@seamusabshere I think we're ready for a (hopefully) final review :)

**Comment by pnomolos** [comment]
@seamusabshere Do you mind doing a final review of this?  Thanks!
